### ISSUE TITLE
Bug in WebTorrent ??

### ISSUE THREAD

**Issue by mukberty** [astavares/bashflix#10]
bashflix "the last dance s01e01 1080p" pt
Searching the best torrent...
Torrent found on The Pirate Bay: No results
Torrent found on YTS: # error:  'yts' - no results
Traceback (most recent call last):
  File "/usr/local/bin/we-get", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/we_get/__init__.py", line 14, in main
    we_get.start()
  File "/usr/local/lib/python3.6/dist-packages/we_get/core/we_get.py", line 237, in start
    sel.run()
  File "/usr/local/lib/python3.6/dist-packages/we_get/core/we_get.py", line 158, in run
    items = run.main(self.pargs)
  File "/usr/local/lib/python3.6/dist-packages/we_get/modules/1337x.py", line 93, in main
    return run.search()
  File "/usr/local/lib/python3.6/dist-packages/we_get/modules/1337x.py", line 59, in search
    data = self.module.http_get_request(url)
  File "/usr/local/lib/python3.6/dist-packages/we_get/core/module.py", line 26, in http_get_request
    res = opener.open(url).read().decode()
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1353, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.6/urllib/request.py", line 1328, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1356, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Torrent found on 1337x: 
Torrent found on RARBG: magnet:?xt=urn:btih:3ada6463c70cdc8333fc9f2ec7275a0322987804&dn=The.Last.Dance.S01E01.1080p.WEB.X264-AMRAP%5Brartv%5D&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2710&tr=udp%3A%2F%2F9.rarbg.to%3A2710&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce
Searching for subtitles...
Collecting videos  [####################################]  100%  The.Last.Dance.Collecting videos  [####################################]  100%                                                   
1 video collected / 0 video ignored / 0 error
Downloading subtitles  [####################################]  100%  The.Last.DaDownloading subtitles  [####################################]  100%                                                   
Some providers have been discarded due to unexpected errors: legendastv, opensubtitles
Downloaded 0 subtitle
1 video collected / 0 video ignored / 0 error
Downloading subtitles  [####################################]  100%  The.Last.DaDownloading subtitles  [####################################]  100%                                                   
Some providers have been discarded due to unexpected errors: legendastv, opensubtitles
Downloaded 0 subtitle
Streaming The.Last.Dance.S01E01.1080p.WEB.X264-AMRAP[rartv]...
verifying existing torrent data...

UNEXPECTED ERROR: If this is a bug in WebTorrent, report it!
OPEN AN ISSUE: https://github.com/webtorrent/webtorrent-cli/issues

DEBUG INFO: webtorrent-cli 3.0.5, webtorrent 0.108.1, node v8.17.0, linux x64, exit 1
/usr/lib/node_modules/webtorrent-cli/node_modules/webtorrent/lib/server.js:79
    const pathname = new URL(req.url, 'http://example.com').pathname
                     ^

ReferenceError: URL is not defined
    at Server.onRequest (/usr/lib/node_modules/webtorrent-cli/node_modules/webtorrent/lib/server.js:79:22)
    at emitTwo (events.js:126:13)
    at Server.emit (events.js:214:7)
    at parserOnIncoming (_http_server.js:660:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)

**Comment by astavares** [comment]
tmp fix: using peerflix
https://github.com/astavares/bashflix/commit/7c8a33a540a9e2224a615b360cc24db6af749c46

reinstall bashflix and try again please

**Comment by mukberty** [comment]
How should I reinstall bashflix (ubuntu 18.04)

**Comment by astavares** [comment]
simply install bashflix again

**Comment by mukberty** [comment]
Thanks a lot.
Works perfectly now!
