### ISSUE TITLE
Unable to load TV Show from name

### ISSUE THREAD

**Issue by mukberty** [astavares/bashflix#11]
I enter- 
bashflix "the last dance s01e01"
OR
bashflix "the last dance s01e01 1080p" pt

and get an error "torrent not found , please enter another query"
BUT 
when I enter 
bashflix "the last dance",
it starts to load s01e07.
What should I do?

**Comment by astavares** [comment]
bashflix "the last dance s01e01 1080p" is working. Install bashflix again please. I will check why with pt subtitles is not working.

**Comment by mukberty** [comment]
I re-installed Bashflix and also have DNS set up but still get the error-

 bashflix "the last dance s01e01 1080p"
Searching the best torrent...
Torrent found on The Pirate Bay: No results
Traceback (most recent call last):
  File "/usr/local/bin/we-get", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/we_get/__init__.py", line 14, in main
    we_get.start()
  File "/usr/local/lib/python3.6/dist-packages/we_get/core/we_get.py", line 237, in start
    sel.run()
  File "/usr/local/lib/python3.6/dist-packages/we_get/core/we_get.py", line 158, in run
    items = run.main(self.pargs)
  File "/usr/local/lib/python3.6/dist-packages/we_get/modules/yts.py", line 83, in main
    return run.search()
  File "/usr/local/lib/python3.6/dist-packages/we_get/modules/yts.py", line 46, in search
    data = json.loads(self.module.http_get_request(url))
  File "/usr/local/lib/python3.6/dist-packages/we_get/core/module.py", line 26, in http_get_request
    res = opener.open(url).read().decode()
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1353, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.6/urllib/request.py", line 1328, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1356, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Torrent found on YTS: 
Traceback (most recent call last):
  File "/usr/lib/python3.6/urllib/request.py", line 1325, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.6/http/client.py", line 1264, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1310, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1259, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 976, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 1425, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib/python3.6/ssl.py", line 817, in __init__
    self.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/we-get", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/we_get/__init__.py", line 14, in main
    we_get.start()
  File "/usr/local/lib/python3.6/dist-packages/we_get/core/we_get.py", line 237, in start
    sel.run()
  File "/usr/local/lib/python3.6/dist-packages/we_get/core/we_get.py", line 158, in run
    items = run.main(self.pargs)
  File "/usr/local/lib/python3.6/dist-packages/we_get/modules/1337x.py", line 93, in main
    return run.search()
  File "/usr/local/lib/python3.6/dist-packages/we_get/modules/1337x.py", line 59, in search
    data = self.module.http_get_request(url)
  File "/usr/local/lib/python3.6/dist-packages/we_get/core/module.py", line 30, in http_get_request
    raise err
  File "/usr/local/lib/python3.6/dist-packages/we_get/core/module.py", line 26, in http_get_request
    res = opener.open(url).read().decode()
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 564, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1368, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.6/urllib/request.py", line 1327, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 104] Connection reset by peer>
Torrent found on 1337x: Error when opening following url.
Could not find torrent for the query the.last.dance.s01e01.1080p. Change the query.

**Comment by astavares** [comment]
I don't think the problem is related to bashflix. Test two different tools, try this
`we-get --search "the last dance s01e01" --target 1337x -L`
and this
`pirate-get -s SeedersDsc -0 -C 'echo "%s"' "the last dance s01e01`
It will probably give the same error. I think the problem seems to be 
`ConnectionResetError: [Errno 104] Connection reset by peer`
Some kind of network broader issue related to python, not sure what. Check if dns is correctly configured.

**Comment by mukberty** [comment]
I get that error when I run the first command, but when I run the second,I get-

Trying https://thepiratebay.org/... Failed  (Blocked mirror detected.)
Trying https://pirateproxy.name... Failed  (Cloudflare protected)
Trying https://tpb16.ukpass.co... Failed  (Cloudflare protected)
Trying https://tpb.sadzawka.tk... Failed  ('utf-8' codec can't decode byte 0x8b in position 1: invalid start byte)
Trying https://www.tpbay.win... Failed  ('utf-8' codec can't decode byte 0x8b in position 1: invalid start byte)
Trying https://thepiratebay.vip... Ok 
 LINK  SEED  LEECH  RATIO        SIZE  UPLOAD       NAME                           
  0    6719    795    8.5    26.7 GiB  01-21 21:22  The Sims 4 v1.60.54.1020 + DLC 
  1    2159    452    4.8     1.9 GiB  10-11 2019   The.Lion.King.2019.1080p.BRRip 
  2    2030    178   11.4     2.6 GiB  03-16 08:29  Star.Wars.Episode.IX.The.Rise. 
  3    2024    403    5.0     1.2 GiB  06-26 2012   Harry Potter and the Sorcerers 
  4    1951    382    5.1     2.0 GiB  06-24 2012   Harry Potter and the Chamber o 
  5    1929    289    6.7     2.1 GiB  06-24 2012   Harry Potter and the Goblet of 
  6    1872    243    7.7     1.9 GiB  06-25 2012   Harry Potter and the Order of  
  7    1872    330    5.7     2.0 GiB  06-24 2012   Harry Potter and the Half Bloo 
  8    1641    203    8.1     3.2 GiB  12-20 2019   The.Witcher.S01.COMPLETE.720p. 
  9    1637     77   21.3     8.8 GiB  10-20 2014   The Sims 4-RELOADED            
  10   1600    289    5.5     1.8 GiB  03-27 09:33  The.Call.of.the.Wild.2020.1080 
  11   1560    171    9.1     1.0 GiB  10-26 2011   Harry Potter And The Deathly H 
  12   1452    224    6.5   998.6 MiB  03-30 2011   Harry Potter and the Deathly H 
  13   1363    284    4.8   874.9 MiB  04-23 02:25  The Last Dance S01E07 Episode  
  14   1347    158    8.5     2.1 GiB  03-14 2014   The Wolf of Wall Street (2013) 
  15   1337    156    8.6     1.9 GiB  06-26 2012   Harry Potter and the Prisoner  
  16   1321    184    7.2     2.2 GiB  03-01 08:42  Jumanji.The.Next.Level.2019.10 
  17   1314     51   25.8     6.4 GiB  10-21 2014   The.Sims.4.Repack-R.G.Mechanic 
  18   1305    143    9.1     2.4 GiB  03-04 2013   The Godfather (1972) 1080p BrR 
  19   1305    190    6.9   933.4 MiB  04-23 02:31  The Last Dance S01E08 Episode  
  20   1261    137    9.2   549.4 MiB  05-22 2010   Harry Potter and the Prisoner  
  21   1260    105   12.0     1.7 GiB  12-31 2011   The Dark Knight (2008) 1080p B 
  22   1230    182    6.8     1.4 GiB  12-22 2019   Star Wars The Rise of Skywalke 
  23   1212    205    5.9     3.7 GiB  07-12 2012   The Lord of the Rings: The Ret 
  24   1202    138    8.7     1.9 GiB  11-15 2014   Guardians of the Galaxy (2014) 
  25   1179    148    8.0  1023.5 MiB  08-21 2012   The Avengers 2012 720p BRrip X 
  26   1164    154    7.6     1.7 GiB  12-20 2019   The.Lighthouse.2019.1080p.WEBR 
  27   1164    181    6.4     1.1 GiB  03-20 15:43  The.Invisible.Man.2020.720p.WE 
  28   1145    146    7.8   904.4 MiB  04-23 02:20  The Last Dance S01E05 Episode  
  29   1140    163    7.0     1.0 GiB  03-24 17:35  The.Gentlemen.2020.720p.WEBRip 
Choosing first result
echo magnet:?xt=urn:btih:0b406697a80e935930f1fbd3df54b21555930c4f&dn=The+Sims+4+v1.60.54.1020+%2B+DLCs+%28selectable%29%2C+MULTi17+%5Banadius%5D&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80&tr=udp%3A%2F%2Ftracker.publicbt.com%3A80&tr=udp%3A%2F%2Ftracker.ccc.de%3A80
magnet:?xt=urn:btih:0b406697a80e935930f1fbd3df54b21555930c4f&dn=The+Sims+4+v1.60.54.1020+%2B+DLCs+%28selectable%29%2C+MULTi17+%5Banadius%5D&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80&tr=udp%3A%2F%2Ftracker.publicbt.com%3A80&tr=udp%3A%2F%2Ftracker.ccc.de%3A80

**Comment by astavares** [comment]
You are being blocked. set DNS to 1.1.1.1 and try again

**Comment by mukberty** [comment]
Thanks.I did so and don't get the old error.
 Now I get-

bashflix "the last dance s01e01"
Searching the best torrent...
Torrent found on The Pirate Bay: _ssl.c:835: The handshake operation timed out
Traceback (most recent call last):
  File "/usr/local/bin/we-get", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/we_get/__init__.py", line 14, in main
    we_get.start()
  File "/usr/local/lib/python3.6/dist-packages/we_get/core/we_get.py", line 237, in start
    sel.run()
  File "/usr/local/lib/python3.6/dist-packages/we_get/core/we_get.py", line 158, in run
    items = run.main(self.pargs)
  File "/usr/local/lib/python3.6/dist-packages/we_get/modules/yts.py", line 83, in main
    return run.search()
  File "/usr/local/lib/python3.6/dist-packages/we_get/modules/yts.py", line 46, in search
    data = json.loads(self.module.http_get_request(url))
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Torrent found on YTS: 
Torrent found on 1337x: # error:  '1337x' - no results
Could not find torrent for the query the.last.dance.s01e01. Change the query.

**Comment by mukberty** [comment]
Another example-

bashflix "crank"
Searching the best torrent...
Torrent found on The Pirate Bay: _ssl.c:835: The handshake operation timed out
Traceback (most recent call last):
  File "/usr/local/bin/we-get", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/we_get/__init__.py", line 14, in main
    we_get.start()
  File "/usr/local/lib/python3.6/dist-packages/we_get/core/we_get.py", line 237, in start
    sel.run()
  File "/usr/local/lib/python3.6/dist-packages/we_get/core/we_get.py", line 158, in run
    items = run.main(self.pargs)
  File "/usr/local/lib/python3.6/dist-packages/we_get/modules/yts.py", line 83, in main
    return run.search()
  File "/usr/local/lib/python3.6/dist-packages/we_get/modules/yts.py", line 46, in search
    data = json.loads(self.module.http_get_request(url))
  File "/usr/local/lib/python3.6/dist-packages/we_get/core/module.py", line 26, in http_get_request
    res = opener.open(url).read().decode()
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1353, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.6/urllib/request.py", line 1328, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1356, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Torrent found on YTS: 
Traceback (most recent call last):
  File "/usr/local/bin/we-get", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/we_get/__init__.py", line 14, in main
    we_get.start()
  File "/usr/local/lib/python3.6/dist-packages/we_get/core/we_get.py", line 237, in start
    sel.run()
  File "/usr/local/lib/python3.6/dist-packages/we_get/core/we_get.py", line 158, in run
    items = run.main(self.pargs)
  File "/usr/local/lib/python3.6/dist-packages/we_get/modules/1337x.py", line 93, in main
    return run.search()
  File "/usr/local/lib/python3.6/dist-packages/we_get/modules/1337x.py", line 59, in search
    data = self.module.http_get_request(url)
  File "/usr/local/lib/python3.6/dist-packages/we_get/core/module.py", line 26, in http_get_request
    res = opener.open(url).read().decode()
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1353, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.6/urllib/request.py", line 1328, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1356, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Torrent found on 1337x: 
Could not find torrent for the query crank. Change the query.

**Comment by mukberty** [comment]
I fixed it by removing DNS.
Thanks for all help!
