### ISSUE TITLE
ReferenceError: URL is not defined (webtorrent-cli)

### ISSUE THREAD

**Issue by jjdevbiz** [astavares/bashflix#9]
> bashflix "westworld s03e01 1080p" en

```
UNEXPECTED ERROR: If this is a bug in WebTorrent, report it!
OPEN AN ISSUE: https://github.com/webtorrent/webtorrent-cli/issues

DEBUG INFO: webtorrent-cli 3.0.5, webtorrent 0.108.1, node v8.17.0, linux x64, exit 1
/home/user/npm/lib/node_modules/webtorrent-cli/node_modules/webtorrent/lib/server.js:79
    const pathname = new URL(req.url, 'http://example.com').pathname
                     ^

ReferenceError: URL is not defined
    at Server.onRequest (/home/user/npm/lib/node_modules/webtorrent-cli/node_modules/webtorrent/lib/server.js:79:22)
    at emitTwo (events.js:126:13)
    at Server.emit (events.js:214:7)
    at parserOnIncoming (_http_server.js:660:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
```

**Comment by jjdevbiz** [comment]
https://github.com/webtorrent/webtorrent-cli/issues/117

Upgrading Node v10 LTS worked.

I also had to set `PATH=$HOME/npm/bin:$PATH` in `$HOME/.bashrc`
